### ISSUE TITLE
Works great on Linux

### ISSUE THREAD

**Issue by qtfkwk** [theodore-s-beers/gloss-word#114]
Ref https://github.com/theodore-s-beers/gloss-word/blob/cf07ae0025ed160bbb2fbd55a95b4bcbcc22d7aa/README.md#L25

Just installed perfectly via `cargo install gloss-word` on Rust 1.74.0 on an up-to-date Debian Linux.

Have been using it lightly and works great so far!

Thanks!

**Comment by theodore-s-beers** [comment]
Thanks; I'm glad to hear it!
